# Generated by Django 4.2.5 on 2023-09-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='type_space',
        ),
        migrations.DeleteModel(
            name='Workspacetype',
        ),
    ]
